language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install .
  # Our test server uses autobahn
  - pip install autobahn
  # For 2.x, our server needs twisted
  - pip install twisted
  # For 3.x where x < 4, our server needs trollius
  - pip install trollius
script: python tests/test_pusherclient.py

