language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install .
  # Our test server uses autobahn
  - pip install autobahn
script: python tests/test_pusherclient.py

